version: '3.8'

services:
  db:
    image: mysql
    container_name: customNameContainerMySQL
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_USER: usernameMysql
      MYSQL_PASSWORD: passMysql
      MYSQL_DATABASE: customNameDATABASE
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: customNamePhpMyAdmin
    depends_on:
      - db
    ports:
      - 8081:80 #Lorsque l'on tape 127.0.0.1:8081, il va aller chercher 127.0.0.1:80 du container
    environment:
      PMA_HOST: db
    networks:
      - dev

  www:
    build: docker
    container_name: customNameProject
    ports:
      - "8001:80"
    volumes:
      - ./docker/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    networks:
      - dev


networks:
  dev:

volumes:
  db-data:
